DSD-DBS/capella-polarion

- pyproject.toml
This should make transitioning to v0.6.x a bit smoother.
> Constrain capellambse to v0.5.x

- capella2polarion/converters/link_converter.py
- tests/conftest.py
We experienced really many errors in Pipelines when generating parent links. This is due to an error which was introduced when we wanted to support nested links for single items [here](https://github.com/DSD-DBS/capella-polarion/blame/e39f922581a706e589ff98e1f5887af1683dfe7a/capella2polarion/converters/link_converter.py#L396). Unfortunately our tests did not fail here, because we check whether the element is a `GenericElement`, but we use the `FakeModelElement` class to perform our tests.
This PR first changed this `FakeModelElement` class to be a MagicMock of `GenericElement` which made 3 tests fail. All these tests are fixed by a minor change in the link resolver
> Fix link generation

- capella2polarion/converters/converter_config.py
- capella2polarion/converters/link_converter.py
- tests/test_elements.py
- log invalid links
- don't try to create them anymore
> feat: Detect invalid link configurations

- capella2polarion/__main__.py
- capella2polarion/connectors/polarion_worker.py
- capella2polarion/converters/document_config.py
- capella2polarion/converters/document_renderer.py
- capella2polarion/converters/polarion_html_helper.py
- tests/conftest.py
- tests/data/documents/combined_config.yaml
- tests/test_cli.py
- tests/test_documents.py
- The render-documents command was simplified and much of the code moved to the DocumentRenderer
- Additional tests now also cover the render-documents command
- If a document fails to get rendered, the job will continue to render the other documents and an Error message will be logged
- If a Polarion request fails, it will get logged and an exception will be raised to stop the job
> Render Documents Enhancements and fail on failed Polarion Requests

- capella2polarion/converters/converter_config.py
- capella2polarion/converters/document_renderer.py
- capella2polarion/converters/link_converter.py
- tests/test_cli.py
- tests/test_elements.py
- Removed obsolete `handle_exchanges` custom link serializers and therefore remove one parameter passed to the serializers
- Mocked the generation of work items in the CLI test as this unnecessarily tests what is already covered in the unit tests
> fix: Remove obsolete link serializers

- capella2polarion/converters/link_converter.py
- tests/test_elements.py
The LinkConfig can not be found when the link role is matched against the role without the prefix.
> fix: Link role for includes

- capella2polarion/__main__.py
- capella2polarion/cli.py
- capella2polarion/converters/converter_config.py
- capella2polarion/converters/element_converter.py
- capella2polarion/converters/link_converter.py
- capella2polarion/converters/model_converter.py
- ci-templates/gitlab/synchronise_elements.yml
- tests/data/model_elements/config.yaml
- tests/test_elements.py
This PR changes the handling of prefixes (type_prefix and role_prefix) such that these are added during loading of the configuration instead of adding them during the serialization of `WorkItem`s or `WorkItemLink`s.
> refactor: Refactor prefixes

- capella2polarion/converters/link_converter.py
- capella2polarion/converters/model_converter.py
- tests/test_elements.py
Backlinks weren't created properly, because we searched for the link config in the work item we wanted to create the back link in. E.g. we searched in a class which was part of a diagram for the config `diagram_elements` to create the back-link
> Fix backlinks

- ci-templates/gitlab/render_documents.yaml
- ci-templates/gitlab/synchronise_elements.yml
This PR adds a `CAPELLA2POLARION_VERSION` parameter to the gitlab ci-templates.
> feat: Add `CAPELLA2POLARION_VERSION` to ci templates

- capella2polarion/__main__.py
- capella2polarion/connectors/polarion_repo.py
- capella2polarion/connectors/polarion_worker.py
- capella2polarion/converters/document_config.py
- capella2polarion/converters/document_renderer.py
- capella2polarion/converters/link_converter.py
- capella2polarion/converters/polarion_html_helper.py
- capella2polarion/converters/text_work_item_provider.py
- capella2polarion/data_models.py
- tests/conftest.py
- tests/data/documents/combined_config.yaml
- tests/data/documents/full_authority_config.yaml
- tests/data/documents/mixed_config.yaml
- tests/data/documents/sections/section1.html.j2
- tests/data/documents/sections/section2.html.j2
- tests/data/documents/templates/document_work_items.html.j2
- tests/test_cli.py
- tests/test_documents.py
- tests/test_elements.py
- tests/test_polarion_worker_documents.py
- tests/test_workitem_attachments.py
In this PR the following additional Features will be added:
- Documents can now be placed in a different project than the model sync work items
- You can define a list of document statuses which you want to allow document updates in
- It is now possible to define text work items in a document
- A text work item can be defined in the document template by using the workitem tag: `<workitem id="id">Some text</workitem>`
- The defined ID must be unique in the document
- The ID will be stored in a custom field of the work item in polarion
- By default the type of these workitems is `text` and the ID will be stored in custom field `__C2P__id`
- You can overwrite this in the config by setting the `text_work_item_type` and `text_work_item_id_field` parameters in your config:
```yaml
- …
```
> Add support for documents in separate projects, status filters and text work items

- .pre-commit-config.yaml
- capella2polarion/cli.py
- capella2polarion/connectors/polarion_repo.py
- capella2polarion/connectors/polarion_worker.py
- capella2polarion/converters/converter_config.py
- capella2polarion/converters/document_config.py
- capella2polarion/converters/document_renderer.py
- capella2polarion/converters/element_converter.py
- capella2polarion/converters/link_converter.py
- capella2polarion/converters/model_converter.py
- capella2polarion/converters/text_work_item_provider.py
- pyproject.toml
- tests/conftest.py
- tests/test_cli.py
- tests/test_documents.py
- tests/test_elements.py
_**Depends on [polarion-rest-api-client #47](https://github.com/DSD-DBS/polarion-rest-api-client/pull/47).**_
> Fix-dependency-handling

- capella2polarion/converters/document_renderer.py
- tests/test_documents.py
Especially in mixed authority documents there might be work items outside the auto generated content. As these already refer a rendering layout, the order of the rendering layout must be kept as is even in the overwrite-layouts mode. Otherwise work items in non auto generated areas might use a wrong rendering layout and can look strange.
> fix: Keep existing rendering layouts in any case

- capella2polarion/converters/link_converter.py
- tests/test_elements.py
When the value behind `capella_attr` is `None`, then we shouldn't fail with an AssertionError. Now the logs are populated.
> fix: Handle `None` return during link creation

- capella2polarion/converters/document_renderer.py
- capella2polarion/converters/text_work_item_provider.py
Some minor changes just for house keeping and to get the pipelines green again
> Minor refactoring

- capella2polarion/__main__.py
- capella2polarion/cli.py
- ci-templates/gitlab/render_documents.yaml
- ci-templates/gitlab/synchronise_elements.yml
- pyproject.toml
- tests/test_cli.py
The CLI usage was simplified by using `envvar`
on any flag or whenever possible.
Special thanks for the hint: @Wuestengecko
> refactor!: Use envvar in CLI options

- capella2polarion/__main__.py
- capella2polarion/connectors/polarion_repo.py
- capella2polarion/connectors/polarion_worker.py
- pyproject.toml
- tests/test_cli.py
- tests/test_elements.py
Instead we create missing WorkItems before the actual element serialization
> feat: Generate WorkItems only once

- capella2polarion/connectors/polarion_worker.py
- capella2polarion/converters/document_renderer.py
- ci-templates/gitlab/synchronise_elements.yml
- tests/test_documents.py
Currently we always send all fields we received from the server with the patch request back to the server. When a user performs changes during the document rendering, it is possible that these custom fields get overwritten by capella2polarion with outdated data. While we cannot guarantee that we don't overwrite content changes made during the rendering, it's easy to avoid overwriting data, we do not actually change in Capella2Polarion. For that reason we will only send `homePageContent`, `renderingLayouts` and optionally `title` and `outlineNumbering` in patch requests in the future.
> feat: Limit document updates to relevant fields

- capella2polarion/connectors/polarion_worker.py
> fix: Use non-`None` values for logging messages

- capella2polarion/converters/element_converter.py
- docs/source/configuration/sync.rst
- docs/source/examples/element_templates/class.html.j2
- tests/test_converter_config.py
- tests/test_elements.py
Also (and this was initially the main intention) added:
- test cases for the config and serializers `add_jinja_as_description` and `add_jinja_fields`
- documentation in the config section for both
> feat: Add `render_params` to jinja serializers

- tests/data/model_elements/config.yaml
- tests/test_converter_config.py
Instead of a minimal typo of an existing name, use an attribute name that makes it obvious that it's supposed to be broken.
Some more context: In the upstream Capella metamodel, the attribute is actually called `exchangedItems`, while capellambse for some reason I don't remember uses `exchange_items`. I intend to unify the spelling of this name (and some others with similar issues) in the not-too-distant future, which would fail `tests/test_converter_config.py::TestConverterConfig::test_read_config_links`, since the "unknown attribute" warning would no longer be emitted.
> Use an obviously broken attribute name for the test

- capella2polarion/converters/element_converter.py
'summary' isn't actually a supported attribute for Requirement objects, and therefore will never be non-empty. Use 'identifier' instead.
> Use Requirement.identifier as fallback display ID
